# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# The environment variables referenced from this docker-compose can be set by
# defining them before running docker-compose, the defaults are set in .env
# file.
#
# Example:
# $ ARCH=arm64v8 docker-compose build ubuntu-bionic-cpp
# $ ARCH=arm64v8 docker-compose run ubuntu-bionic-cpp

version: '3.5'

# TODO(kszucs): include ARCH to cache as well
volumes:
  conda-latest-cache:
  cuda-10.0-cache:
  debian-10-cache:
  ubuntu-18.04-cache:
  ubuntu-16.04-cache:
  ubuntu-14.04-cache:
  fedora-29-cache:

# TODO(kszucs): set shared memory size
# shm_size: 2G

services:

  ################################# C++ #######################################

  conda-cpp:
    image: ${ORG}/${ARCH}-conda-latest-cpp:latest
    build:
      context: ci
      dockerfile: docker/conda-latest-cpp.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-conda-latest-cpp:latest
      args:
        arch: ${ARCH}
        conda: latest
        prefix: /opt/conda
    volumes: &conda-volumes
      - .:/arrow:delegated
      - conda-latest-cache:/build:delegated
    command: &cpp-command >
      /bin/bash -c "
        /arrow/ci/scripts/cpp_build.sh /arrow /build /usr/local &&
        /arrow/ci/scripts/cpp_test.sh  /arrow /build /usr/local"

  cuda-cpp:
    # only amd64 is supported
    image: ${ORG}/${ARCH}-cuda-${CUDA}-cpp:latest
    build:
      context: ci
      dockerfile: docker/cuda-${CUDA}-cpp.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-cuda-${CUDA}-cpp:latest
    volumes: &cuda-volumes
      - .:/arrow:delegated
      - cuda-${CUDA}-cache:/build:delegated
    command: *cpp-command

  debian-cpp:
    image: ${ORG}/${ARCH}-debian-${DEBIAN}-cpp:latest
    build:
      context: ci
      dockerfile: docker/debian-${DEBIAN}-cpp.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-debian-${DEBIAN}-cpp:latest
      args:
        arch: ${ARCH}
    volumes: &debian-volumes
      - .:/arrow:delegated
      - debian-${DEBIAN}-cache:/build:delegated
    command: *cpp-command

  ubuntu-cpp:
    # Possible architectures: amd64, arm64v8
    # Possible distros: 18.04, 16.04, 14.04
    image: ${ORG}/${ARCH}-ubuntu-${UBUNTU}-cpp:latest
    build:
      context: ci
      dockerfile: docker/ubuntu-${UBUNTU}-cpp.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-ubuntu-${UBUNTU}-cpp:latest
      args:
        arch: ${ARCH}
    volumes: &ubuntu-volumes
      - .:/arrow:delegated
      - ubuntu-${UBUNTU}-cache:/build:delegated
    command: *cpp-command

  fedora-cpp:
    image: ${ORG}/${ARCH}-fedora-${FEDORA}-cpp:latest
    build:
      context: ci
      dockerfile: docker/fedora-${FEDORA}-cpp.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-fedora-${FEDORA}-cpp:latest
      args:
        arch: ${ARCH}
    volumes: &fedora-volumes
      - .:/arrow:delegated
      - fedora-${FEDORA}-cache:/build:delegated
    command: *cpp-command

  ############################### C GLib ######################################

  ubuntu-c-glib:
    image: ${ORG}/${ARCH}-ubuntu-${UBUNTU}-c-glib:latest
    build:
      context: ci
      dockerfile: docker/linux-apt-c-glib.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-ubuntu-${UBUNTU}-c-glib:latest
      args:
        base: ${ORG}/${ARCH}-ubuntu-${UBUNTU}-cpp:latest
    volumes: *ubuntu-volumes
    command: &c-glib-command >
      /bin/bash -c "
        /arrow/ci/scripts/cpp_build.sh /arrow /build &&
        /arrow/ci/scripts/c_glib_build.sh /arrow &&
        /arrow/ci/scripts/c_glib_test.sh /arrow"

  ############################### Python ######################################

  conda-python:
    image: ${ORG}/${ARCH}-conda-latest-python-${PYTHON}:latest
    build:
      context: ci
      dockerfile: docker/conda-latest-python.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-conda-latest-python-${PYTHON}:latest
      args:
        org: ${ORG}
        arch: ${ARCH}
        conda: latest
        python: ${PYTHON}
        prefix: /opt/conda
    volumes: *conda-volumes
    command: &python-command >
      /bin/bash -c "
        /arrow/ci/scripts/cpp_build.sh /arrow /build &&
        /arrow/ci/scripts/python_build.sh /arrow &&
        /arrow/ci/scripts/python_test.sh /arrow"

  cuda-python:
    image: ${ORG}/${ARCH}-cuda-${CUDA}-python-3:latest
    build:
      context: ci
      dockerfile: docker/linux-apt-python-3.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-cuda-${CUDA}-python-3:latest
      args:
        base: ${ORG}/${ARCH}-cuda-${CUDA}-cpp:latest
    volumes: *cuda-volumes
    command: *python-command

  debian-python:
    image: ${ORG}/${ARCH}-debian-${DEBIAN}-python-3:latest
    build:
      context: ci
      dockerfile: docker/linux-apt-python-3.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-debian-${DEBIAN}-python-3:latest
      args:
        base: ${ORG}/${ARCH}-debian-${DEBIAN}-cpp:latest
    volumes: *debian-volumes
    command: *python-command

  ubuntu-python:
    image: ${ORG}/${ARCH}-ubuntu-${UBUNTU}-python-3:latest
    build:
      context: ci
      dockerfile: docker/linux-apt-python-3.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-ubuntu-${UBUNTU}-python-3:latest
      args:
        base: ${ORG}/${ARCH}-ubuntu-${UBUNTU}-cpp:latest
    volumes: *ubuntu-volumes
    command: *python-command

  fedora-python:
    image: ${ORG}/${ARCH}-fedora-${FEDORA}-python-3:latest
    build:
      context: ci
      dockerfile: docker/linux-dnf-python-3.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-fedora-${FEDORA}-python-3:latest
      args:
        base: ${ORG}/${ARCH}-fedora-${FEDORA}-cpp:latest
    volumes: *fedora-volumes
    command: *python-command

  ############################# Python Pandas #################################

  conda-python-pandas:
    image: ${ORG}/${ARCH}-conda-latest-python-${PYTHON}-pandas-${PANDAS}:latest
    build:
      context: ci
      dockerfile: docker/conda-latest-python-pandas.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-conda-latest-python-${PYTHON}-pandas-${PANDAS}:latest
      args:
        org: ${ORG}
        arch: ${ARCH}
        conda: latest
        python: ${PYTHON}
        pandas: ${PANDAS}
    volumes: *conda-volumes
    command: *python-command

  ################################## R ########################################



  ################################ Rust #######################################

  debian-rust:
    image: ${ORG}/${ARCH}-debian-10-rust-${RUST}:latest
    build:
      context: ci
      dockerfile: docker/debian-10-rust.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-debian-10-rust-${RUST}:latest
      args:
        arch: ${ARCH}
        rust: ${RUST}
    volumes: *debian-volumes
    command: &rust-command >
      /bin/bash -c "
        /arrow/ci/scripts/rust_build.sh /arrow /build/rust &&
        /arrow/ci/scripts/rust_test.sh /arrow"

  ################################# Go ########################################

  debian-go:
    image: ${ORG}/${ARCH}-debian-10-go-${GO}:latest
    build:
      context: ci
      dockerfile: docker/debian-10-go.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-debian-10-go-${GO}:latest
      args:
        arch: ${ARCH}
        go: ${GO}
    volumes: *debian-volumes
    command: &go-command >
      /bin/bash -c "
        /arrow/ci/scripts/go_build.sh /arrow &&
        /arrow/ci/scripts/go_test.sh /arrow"

  ############################# JavaScript ####################################

  debian-js:
    image: ${ORG}/${ARCH}-debian-10-js-${NODE}:latest
    build:
      context: ci
      dockerfile: docker/debian-10-js.dockerfile
      cache_from:
        - ${ORG}/${ARCH}-debian-10-js-${NODE}:latest
      args:
        arch: ${ARCH}
        node: ${NODE}
    volumes: *debian-volumes
    command: &js-command >
      /bin/bash -c "
        /arrow/ci/scripts/js_build.sh /arrow &&
        /arrow/ci/scripts/js_test.sh /arrow"
