name: C++

# TODO: add file patterns with recursive glob **
on:
  - push
  - pull_request

env:
  # ORG: docker.pkg.github.com/${{ github.repository }}
  ORG: kszucs

jobs:

  docker:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - amd64-conda-latest-cpp
          - amd64-debian-10-cpp
          - amd64-ubuntu-16.04-cpp
          - amd64-ubuntu-18.04-cpp
          - amd64-fedora-29-cpp
        include:
          - name: AMD64 Conda C++
            image: amd64-conda-latest-cpp
            platform: conda
            env:
          - name: AMD64 Debian 10 C++
            image: amd64-debian-10-cpp
            service: debian-cpp
            debian: 10
          - name: AMD64 Ubuntu 16.04 C++
            image: amd64-ubuntu-16.04-cpp
            platform: ubuntu
            ubuntu: 16.04
          - name: AMD64 Ubuntu 18.04 C++
            image: amd64-ubuntu-18.04-cpp
            platform: ubuntu
            ubuntu: 18.04
          - name: AMD64 Fedora 29 C++
            image: amd64-fedora-29-cpp
            platform: fedora
            fedora: 29
    env:
      DEBIAN: ${{ matrix.debian }}
      UBUNTU: ${{ matrix.ubuntu }}
      FEDORA: ${{ matrix.fedora }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Login
        run: |
          docker login \
            -u ${{ github.actor }} \
            -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Pull
        shell: bash
        run: |
          docker-compose pull --ignore-pull-failures ${{ matrix.platform }}-cpp
      - name: Docker Build
        shell: bash
        run: docker-compose build ${{ matrix.platform }}-cpp
      - name: Docker Push
        shell: bash
        run: docker-compose push ${{ matrix.platform }}-cpp
      - name: Docker Run
        shell: bash
        run: docker-compose run ${{ matrix.platform }}-cpp
