name: C++

# TODO: add file patterns with recursive glob **
on:
  - push
  - pull_request

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [conda-cpp]
        conda: [latest]

    env:
      ORG: docker.pkg.github.com/$GITHUB_REPOSITORY
      CONDA: ${{ matrix.conda }}

    steps:
    - name: Checkout Arrow
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Docker Login
      run: |
        docker login docker.pkg.github.com \
          -u $GITHUB_ACTOR \
          -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
    - name: Docker Pull
      run: docker-compose pull --ignore-pull-failures ${{ matrix.service }}
    - name: Docker Build
      run: docker-compose build ${{ matrix.service }}
    - name: Docker Run
      run: docker-compose run ${{ matrix.service }}
    - name: Docker Push
      run: docker-compose push ${{ matrix.service }}
