name: C++

# TODO: add file patterns with recursive glob **
on:
  - push
  - pull_request

env:
  ORG: docker.pkg.github.com/${{ github.repository }}

jobs:

  conda:
    name: Conda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conda: [latest]
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Login
        run: |
          docker login docker.pkg.github.com \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures conda-cpp
      - name: Docker Build
        run: docker-compose build conda-cpp
      - name: Docker Push
        run: docker-compose push conda-cpp
      - name: Docker Run
        run: docker-compose run conda-cpp

  debian:
    name: Debian
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian: [10]
    env:
      DEBIAN: ${{ matrix.debian }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Login
        run: |
          docker login docker.pkg.github.com \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures debian-cpp
      - name: Docker Build
        run: docker-compose build debian-cpp
      - name: Docker Push
        run: docker-compose push debian-cpp
      - name: Docker Run
        run: docker-compose run debian-cpp

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu: [16.04, 18.04]
    env:
      UBUNTU: ${{ matrix.ubuntu }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Login
        run: |
          docker login docker.pkg.github.com \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures ubuntu-cpp
      - name: Docker Build
        run: docker-compose build ubuntu-cpp
      - name: Docker Push
        run: docker-compose push ubuntu-cpp
      - name: Docker Run
        run: docker-compose run ubuntu-cpp

  fedora:
    name: Fedora
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora: [29]
    env:
      FEDORA: ${{ matrix.fedora }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Login
        run: |
          docker login docker.pkg.github.com \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures fedora-cpp
      - name: Docker Build
        run: docker-compose build fedora-cpp
      - name: Docker Push
        run: docker-compose push fedora-cpp
      - name: Docker Run
        run: docker-compose run fedora-cpp
