name: C++

# TODO: add file patterns with recursive glob **
on:
  - push
  - pull_request

jobs:

  conda:
    name: Conda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        conda:
          - latest
    env:
      ORG: docker.pkg.github.com/${{ github.repository }}
      CONDA: ${{ matrix.conda }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Diagnostics
        run: |
          docker version
          env
      - name: Docker Login
        run: |
          docker login docker.pkg.github.com \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures conda-cpp
      - name: Docker Build
        run: docker-compose build conda-cpp
      - name: Docker Run
        run: docker-compose run conda-cpp
      - name: Docker Push
        run: docker-compose push conda-cpp

  debian:
    name: Debian
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian:
          - 10
    env:
      ORG: docker.pkg.github.com/${{ github.repository }}
      CONDA: ${{ matrix.conda }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Diagnostics
        run: |
          docker version
          env
      - name: Docker Login
        run: |
          docker login docker.pkg.github.com \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures debian-cpp
      - name: Docker Build
        run: docker-compose build debian-cpp
      - name: Docker Run
        run: docker-compose run debian-cpp
      - name: Docker Push
        run: docker-compose push debian-cpp

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian:
          - 14.04
          - 16.04
          - 18.04
    env:
      ORG: docker.pkg.github.com/${{ github.repository }}
      CONDA: ${{ matrix.conda }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Diagnostics
        run: |
          docker version
          env
      - name: Docker Login
        run: |
          docker login docker.pkg.github.com \
            -u ${{ github.actor }} \
            -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures ubuntu-cpp
      - name: Docker Build
        run: docker-compose build ubuntu-cpp
      - name: Docker Run
        run: docker-compose run ubuntu-cpp
      - name: Docker Push
        run: docker-compose push ubuntu-cpp

