name: C++

# TODO: add file patterns with recursive glob **
on:
  - push
  - pull_request

jobs:
  build:
    name: Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - conda-cpp
          - debian-cpp
          - ubuntu-cpp
          - fedora-cpp
        include:
          - service: conda-cpp
            ubuntu: latest
          - service: debian-cpp
            ubuntu: 10
          - service: ubuntu-cpp
            ubuntu: 14.04
          - service: ubuntu-cpp
            ubuntu: 16.04
          - service: ubuntu-cpp
            ubuntu: 18.04
          - service: fedora-cpp
            fedora: 29

    env:
      ORG: docker.pkg.github.com/kszucs/arrow
      CONDA: ${{ matrix.conda }}
      DEBIAN: ${{ matrix.debian }}
      UBUNTU: ${{ matrix.ubuntu }}
      FEDORA: ${{ matrix.fedora }}

    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Diagnostics
        run: env
      - name: Docker Login
        run: |
          docker login docker.pkg.github.com \
            -u $GITHUB_ACTOR \
            -p ${{ secrets.GITHUB_PACKAGES_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures ${{ matrix.service }}
      - name: Docker Build
        run: docker-compose build ${{ matrix.service }}
      - name: Docker Run
        run: docker-compose run ${{ matrix.service }}
      - name: Docker Push
        run: docker-compose push ${{ matrix.service }}
