name: C++

# TODO: add file patterns with recursive glob **
on:
  - push
  - pull_request

env:
  # ORG: docker.pkg.github.com/${{ github.repository }}
  ORG: kszucs

jobs:

  docker:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build:
          - conda-latest-cpp
          - debian-10-cpp
          - ubuntu-16.04-cpp
          - ubuntu-18.04-cpp
          - fedora-29-cpp
        include:
          - build: conda-latest-cpp
            name: Conda (latest)
            env:
          - build: debian-10-cpp
            name: Debian (10)
            env: DEBIAN=10
          - build: ubuntu-16.04-cpp
            name: Ubuntu (16.04)
            env: UBUNTU=16.04
          - build: ubuntu-18.04-cpp
            name: Ubuntu (18.04)
            env: UBUNTU=18.04
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Login
        run: |
          docker login \
            -u ${{ github.actor }} \
            -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Pull
        run: ${{ env }} docker-compose pull --ignore-pull-failures conda-cpp
      - name: Docker Build
        run: ${{ env }} docker-compose build conda-cpp
      - name: Docker Push
        run: ${{ env }} docker-compose push conda-cpp
      - name: Docker Run
        run: ${{ env }} docker-compose run conda-cpp
