name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ursabot
      uses: actions/checkout@v1
      with:
        repository: ursa-labs/ursabot
        ref: refs/heads/master
        path: ursabot

    - name: Check Docker
      run: docker --version
    - name: Check Python
      run: python --version
