name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: PWD
      run: pwd
    - name: Checkout Ursabot
      uses: actions/checkout@v1
      with:
        repository: ursa-labs/ursabot
        ref: refs/heads/master
        path: ursabot
    - name: LS
      run: ls -lah
    - name: LS
      run: ls -lah ..
    - name: LS
      run: ls -lah ../..
    - name: ENV
      run: env
    - name: PWD
      run: pwd
    - name: Install Ursabot
      run: pip3 install -e ./ursabot
    - name: Check Ursabot Command
      run: ursabot --help
