name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ursabot
      uses: actions/checkout@v1
      with:
        repository: ursa-labs/ursabot
        ref: refs/heads/master
        path: ursabot
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install Ursabot
      run: pip install -e ../ursabot
    - name: Check Ursabot Command
      run: ursabot --help
    - name: Run Rust Builder
      run: |
        cd ../ursabot/projects/arrow
        ursabot project build \
          --repo https://github.com/$GITHUB_REPOSITORY \
          --branch $GITHUB_REF \
          --commit $GITHUB_SHA \
          "AMD64 Debian 9 Rust 1.35"

