# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Python Minimal Build

on:
  push:
    paths:
      - ".github/workflows/python_minimal.yml"
  pull_request:
    paths:
      - ".github/workflows/python_minimal.yml"
  workflow_dispatch:
    inputs:
      jobs:
        description: "Comma-separated list of job IDs to run"
        required: true
        type: string

permissions:
  contents: read

env:
  ARCHERY_DEBUG: 1

jobs:
  build:
    name: ${{ matrix.id }}
    runs-on: ubuntu-latest
    if: contains(inputs.jobs, matrix.id)
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - id: example-python-minimal-build-fedora-conda
            distro: fedora
            build_type: conda
          - id: example-python-minimal-build-ubuntu-venv
            distro: ubuntu
            build_type: venv
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
      - name: Run minimal build example
        run: |
          cd python/examples/minimal_build
          docker compose run --rm minimal-${{ matrix.distro }}-${{ matrix.build_type }}
