name: Python

# TODO: add file patterns with recursive glob **
on:
  - push
  - pull_request

env:
  # ORG: docker.pkg.github.com/${{ github.repository }}
  ORG: kszucs

jobs:

  docker:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - amd64-conda-latest-python-2.7
          - amd64-conda-latest-python-3.6
          - amd64-conda-latest-python-3.7
          - amd64-debian-10-python-3
          - amd64-ubuntu-16.04-python-3
          - amd64-ubuntu-18.04-python-3
          - amd64-fedora-29-python-3
        include:
          - name: AMD64 Conda Python 2.7
            image: amd64-conda-latest-python-2.7
            platform: conda
            python: 2.7
          - name: AMD64 Conda Python 3.6
            image: amd64-conda-latest-python-3.6
            platform: conda
            python: 3.6
          - name: AMD64 Conda Python 3.7
            image: amd64-conda-latest-python-3.7
            platform: conda
            python: 3.7
          - name: AMD64 Debian 10 Python 3
            image: amd64-debian-10-python-3
            platform: debian
            debian: 10
            python: 3
          - name: AMD64 Ubuntu 16.04 Python 3
            image: amd64-ubuntu-16.04-python-3
            platform: ubuntu
            ubuntu: 16.04
            python: 3
          - name: AMD64 Ubuntu 18.04 Python 3
            image: amd64-ubuntu-18.04-python-3
            platform: ubuntu
            ubuntu: 18.04
            python: 3
          - name: AMD64 Fedora 29 Python 3
            image: amd64-fedora-29-python-3
            platform: fedora
            fedora: 29
            python: 3
    env:
      PYTHON: ${{ matrix.python }}
      DEBIAN: ${{ matrix.debian }}
      UBUNTU: ${{ matrix.ubuntu }}
      FEDORA: ${{ matrix.fedora }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Login
        run: |
          docker login \
            -u ${{ github.actor }} \
            -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Pull
        shell: bash
        run: |
          docker-compose pull --ignore-pull-failures ${{ matrix.platform }}-cpp
          docker-compose pull --ignore-pull-failures ${{ matrix.platform }}-python
      - name: Docker Build
        shell: bash
        run: |
          docker-compose build ${{ matrix.platform }}-cpp
          docker-compose build ${{ matrix.platform }}-python
      - name: Docker Push
        shell: bash
        run: docker-compose push ${{ matrix.platform }}-python
      - name: Docker Run
        shell: bash
        run: docker-compose run ${{ matrix.platform }}-python
