name: Rust

on:
  push:
  #   paths:
  #     - 'rust/**'
  pull_request:
  #   paths:
  #     - 'rust/**'

jobs:
  docker:
    name: AMD64 Debian Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly-2019-09-25]
    env:
      RUST: ${{ matrix.rust }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures debian-rust
      - name: Docker Build
        run: docker-compose build debian-rust
      - name: Docker Run
        run: docker-compose run debian-rust
      - name: Docker Push
        if: github.event_name == 'push' &&
            secrets.DOCKERHUB_USER &&
            secrets.DOCKERHUB_TOKEN
        shell: bash
        run:
          docker login \
            -u ${{ secrets.DOCKERHUB_USER }} \
            -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose push debian-rust

  macos-windows:
    name: AMD64 ${{ matrix.name }} Rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-10.14
          - windows-2019
        include:
          - os: macos-10.14
            name: MacOS 10.14
            rust: nightly-2019-09-25
          - os: windows-2019
            name: Windows 2019
            rust: nightly-2019-09-25
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            override: true
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build
        shell: bash
        run: ci/scripts/rust_build.sh $(pwd) $(pwd)/rust/target
      - name: Test
        shell: bash
        run: ci/scripts/rust_test.sh $(pwd)
