name: Rust

# TODO: add file patterns with recursive glob **
on:
  - push
  - pull_request

env:
  # ORG: docker.pkg.github.com/${{ github.repository }}
  ORG: kszucs

jobs:

  debian:
    name: Debian
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly-2019-09-25]
    env:
      RUST: ${{ matrix.rust }}
    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Docker Login
        run: |
          docker login \
            -u ${{ github.actor }} \
            -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Pull
        run: docker-compose pull --ignore-pull-failures debian-rust
      - name: Docker Build
        run: docker-compose build debian-rust
      - name: Docker Push
        run: docker-compose push debian-rust
      - name: Docker Run
        run: docker-compose run debian-rust
